# creating a file using "myfile.yml"
---
- hosts: all
  become: yes
  tasks:
    - name: Create File using another file
    - include_tasks: myfile.yml # name of the file where file creation code is written
