# This playbook is about Error Handling
---
- hosts: all
  become: yes
  tasks:
    - name: Install git
      apt:
        name: git
        state: absent
  
    - name: Install wget
      apt:
        name: wget
        statee: present # it will give an Error because of spelling mistake in "statee"
    
      # Error Handling
      ignore_error: yes 


