# This playbook is about Error Handling
---
- hosts: all
  become: yes
  tasks:
    - name: Install git
      apt:
        name: git
        state: absent
  
    - name: Install wget
      apt:
        name: wget
        statee: present  # It will give error due to spelling mistake in 'statee'
    
      # Error Handling
      ignore_errors: yes  # This will ignore the error
