# This is to get file from internet (downloading file from web) using get_url module
---
- hosts: all
  become: yes
  tasks: 
  - name: I want to download file from internet using "get_url"
    get_url:
       url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz 
       dest: /home/vamsi/apache-tomcat-10.0.20.tar.gz # destination location in ansible node
       force_basic_auth: yes # to authenticate to that website

      