# This playbook is about installing webserver using variables file
---
- hosts: web_servers
  become: yes

  tasks:
  - include_vars: variables.yml
  - name: Installing webserver 
    apt:
       name: '{{package_name}}' 
       update_cache: yes
       state: latest

