# This is to replace the index.html file with custom file
# pre-requisites: custom index file with .j2 extension

---
- hosts: all
  become: yes
  tasks: 
    - name: Copy Custom index file on Ansible node
      template: 
        src: custom_index.j2  # custom index file present in current working directory
        dest: /var/www/html/index.html
