# This playbook is to install webservers on nodes based on there family 
---
- name: install webservers on node based on OS_family
  hosts: all
  become: yes
  tasks:
  - name: I want to install apache2 webserver on ansible ubuntu node
    apt: 
       name: apache2
       state: present 
    when: ansible_os_family=="Debian"

  - name: I want to start the webserver
    service: 
       name: apache2
       state: started 
    when: ansible_os_family=="Debian"
