# This playbook is about to demonstarte about command module
---
- hosts: web_servers
  become: yes
  tasks:
  # Executing the linux command
  - name: I want to execute Linux Commands on Ansible node
    command: hostname -f 
    register: my_first_task_result # used to hold the command output

  # To display the results on console
  - name: I want to Display the Linux command output
    debug:
      msg: "{{my_first_task_result}}"
  
