# This playbook is about installing webserver using variables file
---
- hosts: all # mentione host details here or in other file
  become: yes

  tasks:
  - include_vars: myvars.yml
  - name: Installing apache2 
    apt:
      name: "{{package_name}}"
      update_cache: yes
      state: latest
  
  - name: start service 
    service:
      name: "{{package_name}}"
      state: started
      

