# This is just a sample playbook
---
- hosts: web_servers
  become: yes
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present
  - name: Start nginx
    service:
      name: nginx
      state: started


